import type { CatalogItemRecord, ProviderRecord } from "./settleside.schemas";

const nowIso = () => new Date().toISOString();

function withTimestamp<T extends object>(value: T) {
  const timestamp = nowIso();
  return { ...value, createdAt: timestamp, updatedAt: timestamp };
}

export const SEED_PROVIDERS: ProviderRecord[] = [
  withTimestamp({
    key: "ikea-ae",
    name: "IKEA UAE",
    category: "Furniture and home essentials",
    website: "https://www.ikea.com/ae/en/",
    coverageCities: ["Abu Dhabi", "Dubai", "Sharjah"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "manual",
    commercialModel: "unknown",
    integrationStatus: "api-needed",
    nextStep: "Confirm affiliate access, catalog feed, and delivery slot APIs.",
    priority: "high",
    active: true,
  }),
  withTimestamp({
    key: "amazon-ae",
    name: "Amazon.ae",
    category: "Home essentials",
    website: "https://www.amazon.ae/",
    coverageCities: ["Abu Dhabi", "Dubai"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "manual",
    commercialModel: "referral",
    integrationStatus: "api-needed",
    nextStep: "Evaluate Product Advertising API and checkout handoff rules.",
    priority: "high",
    active: true,
  }),
  withTimestamp({
    key: "du",
    name: "du",
    category: "Internet and utilities",
    website: "https://www.du.ae/",
    coverageCities: ["Abu Dhabi", "Dubai"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "manual",
    commercialModel: "commission",
    integrationStatus: "api-needed",
    nextStep: "Map address eligibility, package availability, and appointment booking.",
    priority: "high",
    active: true,
  }),
  withTimestamp({
    key: "etisalat",
    name: "e& UAE",
    category: "Internet and utilities",
    website: "https://www.etisalat.ae/",
    coverageCities: ["Abu Dhabi", "Dubai"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "manual",
    commercialModel: "commission",
    integrationStatus: "api-needed",
    nextStep: "Map address eligibility, package availability, and appointment booking.",
    priority: "high",
    active: true,
  }),
  withTimestamp({
    key: "movers-network",
    name: "Vetted movers network",
    category: "Movers and shipping",
    website: "",
    coverageCities: ["Abu Dhabi"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "email",
    commercialModel: "referral",
    integrationStatus: "partner-ready",
    nextStep: "Collect rate cards, quote fields, insurance limits, and booking SLAs.",
    priority: "high",
    active: true,
  }),
  withTimestamp({
    key: "settleside-ops",
    name: "SettleSide operations desk",
    category: "Move planning",
    website: "",
    coverageCities: ["Abu Dhabi"],
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    leadMethod: "manual",
    commercialModel: "markup",
    integrationStatus: "manual",
    nextStep: "Replace manual fulfillment with partner-specific workflow automation.",
    priority: "medium",
    active: true,
  }),
];

export const SEED_CATALOG_ITEMS: CatalogItemRecord[] = [
  withTimestamp({
    id: "mattress-hybrid-queen",
    providerKey: "ikea-ae",
    type: "product",
    category: "Mattress",
    name: "Hybrid Memory Foam Queen",
    description: "Core bedroom setup item with delivery window tracking.",
    price: "AED 2,199",
    currency: "AED",
    unit: "one-time",
    city: "Abu Dhabi",
    availability: "In stock",
    deliveryWindow: "2-4 days",
    rating: 4.7,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Partner or affiliate fee to confirm",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "sofa-linen-sand",
    providerKey: "settleside-ops",
    type: "product",
    category: "Sofa",
    name: "Linen 3-Seater - Sand",
    description: "Starter living-room option sourced through the operations desk.",
    price: "AED 3,150",
    currency: "AED",
    unit: "one-time",
    city: "Abu Dhabi",
    availability: "Limited stock",
    deliveryWindow: "5-7 days",
    rating: 4.5,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Markup or concierge fee",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "kitchen-starter-box",
    providerKey: "amazon-ae",
    type: "product",
    category: "Kitchen starter",
    name: "30-piece essentials box",
    description: "Basic cookware, tableware, and first-week kitchen supplies.",
    price: "AED 489",
    currency: "AED",
    unit: "one-time",
    city: "Abu Dhabi",
    availability: "In stock",
    deliveryWindow: "1-2 days",
    rating: 4.6,
    active: true,
    source: "seed",
    checkoutMethod: "affiliate-link",
    checkoutUrl: "",
    commissionModel: "Affiliate fee to confirm",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "fiber-1gbps-no-contract",
    providerKey: "du",
    type: "product",
    category: "Internet",
    name: "1 Gbps fiber - no contract",
    description: "Home internet package requiring address eligibility check.",
    price: "AED 389/mo",
    currency: "AED",
    unit: "monthly",
    city: "Abu Dhabi",
    availability: "Address check needed",
    deliveryWindow: "3-5 days",
    rating: 4.3,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Commission to confirm",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "movers-shipping",
    providerKey: "movers-network",
    type: "service",
    category: "Movers & shipping",
    name: "Local and international mover quote",
    description: "Compare quotes from vetted international and local movers.",
    price: "Quote required",
    currency: "AED",
    unit: "per move",
    city: "Abu Dhabi",
    availability: "12 providers",
    deliveryWindow: "Quote in 24 hours",
    rating: 4.7,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Referral fee",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "cleaning",
    providerKey: "settleside-ops",
    type: "service",
    category: "Cleaning",
    name: "Move-in deep clean",
    description: "Move-in and move-out deep cleans booked in a few taps.",
    price: "From AED 450",
    currency: "AED",
    unit: "per booking",
    city: "Abu Dhabi",
    availability: "8 providers",
    deliveryWindow: "Next-day slots",
    rating: 4.5,
    active: true,
    source: "seed",
    checkoutMethod: "booking",
    checkoutUrl: "",
    commissionModel: "Commission or markup",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "internet-utilities",
    providerKey: "du",
    type: "service",
    category: "Internet & utilities",
    name: "Internet and utilities setup",
    description: "Set up fiber, mobile, power, and water on day one.",
    price: "Plan dependent",
    currency: "AED",
    unit: "monthly",
    city: "Abu Dhabi",
    availability: "Local telcos",
    deliveryWindow: "3-5 days",
    rating: 4.3,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Commission to confirm",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "handyman-install",
    providerKey: "settleside-ops",
    type: "service",
    category: "Handyman & install",
    name: "Move-in handyman bundle",
    description: "Curtains, TV mount, assembly, booked to your move-in date.",
    price: "From AED 250",
    currency: "AED",
    unit: "per booking",
    city: "Abu Dhabi",
    availability: "20+ pros",
    deliveryWindow: "Same-week slots",
    rating: 4.4,
    active: true,
    source: "seed",
    checkoutMethod: "booking",
    checkoutUrl: "",
    commissionModel: "Commission or markup",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "insurance",
    providerKey: "settleside-ops",
    type: "service",
    category: "Insurance",
    name: "Renters and contents insurance referral",
    description: "Renters and contents cover from licensed brokers.",
    price: "Quote required",
    currency: "AED",
    unit: "annual",
    city: "Abu Dhabi",
    availability: "5 brokers",
    deliveryWindow: "Policy in 48 hours",
    rating: 4.4,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Referral fee",
    lastSyncedAt: nowIso(),
  }),
  withTimestamp({
    id: "storage",
    providerKey: "movers-network",
    type: "service",
    category: "Storage",
    name: "Short-term storage quote",
    description: "Short-term storage for the awkward gap between homes.",
    price: "Quote required",
    currency: "AED",
    unit: "monthly",
    city: "Abu Dhabi",
    availability: "Local and national",
    deliveryWindow: "2-3 days",
    rating: 4.4,
    active: true,
    source: "seed",
    checkoutMethod: "lead",
    checkoutUrl: "",
    commissionModel: "Referral fee",
    lastSyncedAt: nowIso(),
  }),
];
